---
---
title: "lab01 markdown"
output: html_document
date: "2023-09-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
visitors <- read_csv("data/UK-visitor-numbers.csv")
```

```{r visitors}
#Question 1
visitors %>% count(region)

visitors %>% count(admission, setting)
```

```{r visitors}
#Question 2
class(visitors$n_2022)
visitors %>% summarise_all(class)
```

```{r visitors}
#Question 3
visitors %>% arrange(desc(n_2022))
visitors %>% arrange(desc(n_2021), n=10)
```

```{r visitors}
#Question 4
filter(visitors, n_2022 == 565772)
count(visitors, n_2022 > 1000000)
```

``` {r visitors}
#Question 5
visitors %>% filter(
  setting == "O",
  admission == "Members",
  region == "Yorkshire and the Humber",
  n_2022 > 100000
) %>% count()

visitors %>% filter (
  n_2022 > 50000,
  n_2022 < 100000
) %>%
  count()

visitors %>% count(
  region) %>% 
  filter (
    n > 50
) %>% count()

```

```{r visitors}
#Question 6
visitors %>% summarise(
mean(n_2022),
median(n_2022),
mean(n_2021, na.rm = TRUE),
median(n_2021, na.rm = TRUE)
)
```

```{r visitors}
#Question 7
  visitors %>% group_by(
    setting) %>% summarise(
      mean(n_2022),
      median(n_2022)
    )
```

```{r visitors}
visitors_nation <- visitors %>% mutate(
  nation = case_when(
    region == "Northern Ireland" ~ "Northern Ireland",
    region == "Scotland" ~ "Scotland", 
    region == "Wales" ~ "Wales",
    TRUE ~ "England"
  ))

visitors_nation %>% 
  group_by(nation) %>%
  summarise("IQR_2022" = IQR(n_2022)
            )
```
  